spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: root

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET}